### ISSUE TITLE
Some questions about origin paper

### ISSUE THREAD

**Issue by lazyeden** [LinyangLee/Layer-Weight-Poison#2]
I would like to ask if $H^i$ and $\hat{H}^i$ in formula 3 and formula 4 of the paper are reversed？

**Comment by huangtiansheng** [comment]
Same question here...

**Comment by LinyangLee** [comment]
Sorry for the late response, yes the $H^i$ and $\hat{H}^i$ are reversed, which is a writing error. 
We expect  $H^i$ to be correctly classified and $\hat{H}^i$ to be misled by triggers.
